### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by Shurik244** [faheel/youtube-scraper-api#10]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/API/YTScraper/scraper/api.py", line 135, in <module>
    app = App(routes=routes)
  File "/root/.local/share/virtualenvs/YTScraper-6Z8BojAV/lib/python3.8/site-packages/apistar/server/app.py", line 54, in __init__
    routes = routes + self.include_extra_routes(schema_url, docs_url, static_url)
  File "/root/.local/share/virtualenvs/YTScraper-6Z8BojAV/lib/python3.8/site-packages/apistar/server/app.py", line 82, in include_extra_routes
    Route(
  File "/root/.local/share/virtualenvs/YTScraper-6Z8BojAV/lib/python3.8/site-packages/apistar/server/core.py", line 17, in __init__
    self.link = self.generate_link(url, method, handler, self.name)
  File "/root/.local/share/virtualenvs/YTScraper-6Z8BojAV/lib/python3.8/site-packages/apistar/server/core.py", line 20, in generate_link
    fields = self.generate_fields(url, method, handler)
  File "/root/.local/share/virtualenvs/YTScraper-6Z8BojAV/lib/python3.8/site-packages/apistar/server/core.py", line 70, in generate_fields
    elif issubclass(param.annotation, types.Type):
  File "/usr/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class

Idk how to fix that

**Comment by faheel** [comment]
This is most likely due to incompatible Python versions. You can check if it works with Python versions before 3.8.
